---
title: Introduction to Tableau
author: ''
date: '2020-03-30'
slug: introduction-to-tableau
categories: ["Tableau"]
tags: []
subtitle: ''
summary: 'A beginner-friendly introduction to Tableau with a screencast on YouTube. Learn the basics of Tableau (dimensions vs. measures, formatting, introductory calculations, tooltips) as well as details on how to create several different chart types, including stacked bar charts, charts with a dual axis, and more.'
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: true
---

## Screencast video

A bunch of people have been asking me for some kind of Tableau tutorial, so I'm experimenting with a screencast video on YouTube! The video should be embedded below and is also [available here](https://www.youtube.com/watch?v=fN7vAfeN0_E&feature=youtu.be). The sample data set I use will probably be familiar to you if you've ever done any of my R tutorials, it's a CSV that's available to download [here](https://github.com/hockey-graphs/HG_intro_tutorial/blob/master/PHI_tutorial_data.csv) (to download from Github, just hold down Alt and click the Raw button). A (lightly-edited) transcript with time stamps is available below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/fN7vAfeN0_E" frameborder="0" allowfullscreen></iframe>

## Introduction (0:35)

Just as a disclaimer before we get started, I had mentioned that I had done a lot of R tutorials, and there are a lot of people who want to discuss which is better and which is worse, Tableau vs. R vs. many other programs for visualizing data, and I personally don't really have a lot of interest in that argument. Both Tableau and R have strengths and weaknesses, advantages and disadvantages, and I really don't think there's any harm in having more tools in your toolbox. Tableau in particular is really useful free tool for visualizing data and is particularly beginner-friendly. 

This is Tableau Public. Tableau does have a lot of various enterprise options, but Tableau Public is the version that is free. The main limitation with Tableau Public is that you cannot save anything locally to your computer. Along with downloading Tableau Public you get a Tableau Public account, and everything gets saved to that account. It is true that you can hide visualizations, I have certain older visualizations that I don't really want anyone to see anymore. I have them hidden but they still exist on the Internet, so this is not a good solution if you are working with confidential data or data that you don't want anyone to see.

We're going to start off by connecting to data, which you can do with this big Connect to Data button. The data we're going to use for this is the data that I use for most of my tutorials, so I'm sorry if you're bored with this data. It is a CSV file that's available on my Github, it's hockey data, four games from the past NHL season, four Philadelphia Flyers games from November 2019. It's play-by-play data I have scraped, and that's what we'll be using here.

Once you load in data here, we're just going to be working with one csv file, but you can bring in more files and you can do joins and unions and all of those sorts of things. You can also modify your data fields here in this pane, you can do simple pivots to make your data wider or longer. You can also modify your data fields within the worksheets, which we're going to do now. Anytime you want to get back to your data source, just select the Data Source button in the lower left corner.

## Dimensions and measures (3:45)

A big part of learning Tableau is just understanding how it works, and once you understand that, you can more intuitively understand how to build visualizations. The hardest part of learning Tableau is figuring out what they call everything and how to use their language to build the visualizations that you need. But in general, here it will show all your data fields as dimensions, which are string or character variables, and measures, which are numbers. Tableau makes its best guess when it reads in data, but you can make changes. In this example, it read our season variable as a number, but I don't really want it as a number, I would prefer that it be a string variable. All you have to do is right-click on the data field and select Change Data Type, and you can change it to a string. It will still leave it as a measure, but all you have to do is drag it up to the dimension section. You can do the same the other way, as well. This data set contains x and y coordinates for shot locations, and while it automatically brought them in as strings, maybe we want them as numbers. Again, just select both, right click, select Change Data Type and select whole number. Then move them to measures.

## Building a bar chart (5:25)

The first thing to learn in any data visualization program is how to make a super-simple bar chart. We're going to look at the number of shots each player took. If you just double-click any variable, like we do here with Event Player 1, it will automatically bring it over into the view onto Rows. We're also going to filter this view because we're only interested in shots on goal for this particular bar graph. So we're going to drag the Event Type field to filter and then select GOAL and SHOT. You can get fairly complicated with your filters (that will be an overarching theme in this entire tutorial, everything I show you does have more complex options), but we're just choosing two. 

One of the most useful fields in Tableau is this Number of Records field, which will show up in every data set under measures. It just counts the number of rows and we'll bring that in by double-clicking it. Now we have a list of players and their shots. We probably want to sort this, so we're going to right-click on this Event Player 1 field (in Tableau these are called pills) and select Sort. There are lots of ways to sort, but we're going to sort by field, by descending, and by the default, which is the sum of the number of records.

One of the nice things about Tableau is that it's got this icon in the upper right called Show Me that has a bunch of different graph types you can select. Now when I build visualizations in Tableau I don't really use these because I know how to build the charts and graphs that I want, but it's really useful for beginners because it teaches you how Tableau builds visualizations. If I click on bar graph, watch what happens on the screen: all it did was move Number of Records from text to columns.

One of my biggest tips for people who are learning Tableau is to make as many changes as you can to these default settings because everyone's default Tableau graph looks the same. Every one looks the same, with this font and this tooltip (which is what shows up when you hover over a data point) and the blue bars. There's a lot of customization you can do in Tableau, and as we go through these several chart types that we're going to build, we're going to show some of those options. The first thing I'm interested in is I want to have a label on these bars. All I have to do is drag my Number of Records field to the label field. If I want to make other changes, you can go into the Format menu, then select Workbook. When you want to make changes, you can do it either at the full workbook level (which I would recommend for changes you'll want everywhere, like changing the font) or the individual worksheet level. One reminder: if you're sharing these visualizations on Tableau Public, which most people are, you can't necessarily use tons of fancy fonts because the people viewing your visualizations might not have those fonts. There's a list of fonts that are global on Tableau Public, which you can find via Google, but right now just to make a change, we're using super-plain Arial. This will change the font throughout the entire workbook. If there are individual changes you want to make, you can change the font for those things separately and it will override the global option.

Just to show how that would work, if we wanted to modify these row headers, all we have to do is right-click and select Format. Now we can change the font, we can make it bold and larger, etc. I personally don't like these field labels, so I always right-click and hide those. 

This is kind of a big bar chart, so if I only want to show players with at least five shots, all you have to do is right-click on the Number of Records field and select Filter. We're going to select At Least and filter to only show players that have at least five shots, and that will make the bar chart much smaller. Again, the standard bar chart color is always blue, so if you want to change what this bar color is, you have a few options. You can select the color field here in the Marks section, or you can bring in another data field and drop it onto this color option. Say that we want to take this Event Team field, we can drag it over to the color option. Blue and orange is the standard Tableau color palette, so I would highly recommend changing it. Just select the colors, you can add custom colors by hex codes, you can upload your own color palettes, or you can use a Tableau color palette. We'll make Philadelphia orange and make Vancouver blue. This is a pretty ugly graph now, but it shows you some of the things you can do when making a bar chart.

The next thing I would want to change is this axis so that it actually reads something meaningful. You can do this by right-clicking on the axis and selecting Edit. You can change what you want the range of the axis to be, since in some cases you might not want to show zero, I'm just going to change the axis title to Total Shots on Goal. I personally also have a lot of opinions, like most of you probably do, on how I want my graphs to look, and Tableau allows you to customize just about everything with how the lines and axes look. You can change these on each individual sheet, but I prefer to do it by going to Format -> Workbook because I know I like these changes across the workbook. I generally don't like grid lines so I can take those off, I can get rid of axis ticks which I also don't like, and I can change up what the axis lines look like. Again, there are a lot of different formatting options, but I recommend using the Format -> Workbook method for the global options you want because it will make it much easier. 

Lastly, one of the nice things about Tableau that I mentioned before is that you have these tooltips if you hover over a data point. These are very customizable and I recommend that you customize them because there are a lot neat things you can do with them, and it makes your Tableau workbook look a little more custom, a little less straight-out-of-the-box.

If you don't like the tooltips in general, you can find them by clicking on the Tooltips button on this marks card, you can just unclick "Show tooltips" and it will just remove them. But again, you can really play with these. All of the fields that are in your view are available by clicking the Insert button, and you can also add more fields to your view if you wanted to have access to them in your tooltip. We could rewrite these, and I think it's nice to have more detail in your tooltips.

## Side-by-side bar chart (15:30)

We'll create a new sheet down here, and we'll take our Game ID field (a unique identifier for each game) into Rows. We're again going to use our Event Type filter and filter down to to SHOT and GOAL. A neat thing with Tableau filters (though we're not going to experiment with this here) is that you can apply these filters to multiple worksheets, which is really useful so you don't have to keep creating filters. We're going to add the number of records onto Columns, which will make a bar chart. Up here in the menu bar, there's an option to swap rows and columns to make a column bar chart. Right now this is showing the total number of shots on goal, for both teams, for each game. If I wanted to see it by team and create a side-by-side bar chart, all I have to do is drag this Event Team data field over to Columns, then it automatically creates a side-by-side bar chart for me. Here at the bottom are all of the teams in these games, and the only thing I don't like about this is that I'd like it better if the Philadelphia column was to the right in every section. It's not because it's showing the teams in alphabetical order, but we can change this by going to the Event Team data field, click the arrow and then click sort, we can sort manually and I can drag Philadelphia to the bottom so that it's the right-hand column in each of these sections, which I find easier to read.

Say we want to color these bars by which team it is. We can do that by bringing this Event Team dimension, just dragging it over to color on the Marks card. I don't particularly like this because it assigned a different color to each team, which I don't think for this visualization is necessary. If I wanted all the other teams besides Philadelphia to be gray, I could just go through and change every other team color manually, but that's a little too much work. Instead I'm going to create a calculated field that we're going to keep using through this tutorial. Under the Analysis menu, go to Create Calculated Field. You can create a lot of different calculations in Tableau, but this is going to be a super simple if statement: IF Event Team = "PHI" THEN "Y" ELSE "N" END. Drag this new PHI calculation onto color, replacing the Event Team pill that was already there. This is better because Philadelphia is one color and all the other teams are another color. I'm going to change the specific colors, also. The good news is when you change colors in Tableau, those colors will maintain every time you use the field. Here we're setting the Philadelphia color to be orange and the "other team" color to be light gray. If you use this field in another visualization, which we will do, it will maintain these colors.

Just as a reminder, you can format any of these options that are here in the view. If we wanted to change this Game ID field, we could right-click and select Format to make this bold, if we wanted to make Event Team italic, we can do that. Another neat feature in Tableau when you're dealing with dimensions is the concept of aliases. If, for example, I don't want these Game ID values to show up like this, all I have to do is right-click on it and I can edit the alias. I could call this "Carolina Game" or "Game 27" or whatever. These aliases can be really useful if the way your data comes in doesn't necessarily match the way you want to display it. If you want to get rid of abbreviations and things like that, the aliases can help. You can also find them if you navigate to that data field in the dimensions pane, right-click and select Aliases. You can set them all at once.

One last thing that I wanted to show on this particular graph is the way that filters work. This graph is showing the number of shots on goal for every team in every game, but say we wanted to filter that further, we can drag in this Game Strength State field onto Filter. Say I only wanted to see shots that happened at 5v5, or I can go over to the data field in the Filter section, hit the arrow, and select Show Filter. That will add it to the view. Again, there are a lot of formatting options for the filter which you can find by selecting the little arrow in the title section. For example, I can select Single Value and List, which allows you to easily change the filter selections in your view.

## Stacked bar chart (23:35)

We'll open another new sheet and will work with Game ID again. We'll bring Game ID to columns, and we'll use our favorite Number of Records field and we'll bring that to Rows. This has automatically made a column bar chart with all of the rows for each Game ID. We are not interested in all of those Event Types, so we'll bring Event Type to Filter and filter down to just shot attempts: BLOCK, GOAL, MISS, SHOT. Let's say we want to create a stacked bar chart where I can see the percentage of each event type for each game. So how we would build this is that we need to take the Event Type field again and bring that over to Color, which will add the color feature to our bar chart with a different color for each event type. We'll change the color palette, I mentioned there are a bunch of built-in color palettes within Tableau, or you can also create your own. This is closer to what we want, but this is still showing total numbers while we want to see a percentage.

In order to do that, we need to go up to our Number of Records pill on our Rows shelf, click the little arrow, and we'll go down to the table calculation section. I know I sound like a broken record here, but here in this tutorial we're just skimming the surface of what Tableau can do. You can get pretty complicated with your table calculations, but we're just going to select Quick Table Calculation and then Percent of Total. Now these percentages don't look exactly right, and that just means they aren't computing along the right data field. So all we have to do is click the arrow on the Number of Records pill and you'll see a new option in this menu called Compute Using. This tells Tableau how you want this percentage to be calculated. We want it to be calculated across Event Type, so we'll select that, and then that will make the stacked bar that we want. 

If we want to add a label to these bars, all we have to do is again, select the Number of Records field from the measures section and drag that over to Label. That will label all the individual sections, but it just labels it with the raw number. You might want to show that (I often show the raw number as well as the calculation in my labels), but if we just want the percentage label, add the same Quick Table Calculation to this label. You can select the Format option on the Label pill if you wanted to change the number format. The labels, similar to the tooltips, are very flexible and you can add a lot of information. If we also wanted to add Event Type to the label, we could absolutely do that. Drag in another instance of the Event Type field and drag it onto Label. It will show up automatically, and if you want to edit it further, just click the Label card to edit and format the text.

## Line graph (28:30)

We have a Game Date field here. Working with dates in Tableau, just like working with dates in any other program, has a bit of a learning curve to it. A lot of that depends on how your dates are formatted in the data source as you bring them into Tableau, but Tableau has a lot of functionality around dates. Here, we're going to bring our Game Date field onto Columns. You can see kind of immediately that this looks weird, this just shows the year of the Game Date. But we can change that by selecting the down arrow on the pill and there are lots of options for how to display the date. We want to display the full date, so we'll select Day. These are the four dates that these games were played. This also looks a little weird, but we're going to fix that in a minute. Also, one of my biggest Tableau lessons is don't be afraid when your visualization looks weird because a lot of them look weird and bad at the beginning and just take some finagling to make them look good. This looks weird, don't worry about it. 

We're going to move our Number of Records field to Rows, and that's automatically going to make a basic line graph. This does this because it recognizes the axis as a date. Over on the marks card, you can see that the line option is the automatic option. You can change this here, we could make it into a bar chart, we could make it into circles, but we're good with the Line option. These games dates aren't showing up exactly as how I want them because it's a little misleading to add these extra dates in here. These four games were only on the odd number dates, and it's incorrect data-wise to be showing these other dates. I understand why Tableau is doing this, it thinks it's being helpful, but it's really not. That's another common thing with Tableau, you often have to figure out ways to override the ways that it tries to help you that you don't agree with. We can fix this particular problem by going back to the Game Date pill, selecting the down arrow, and then change it to Discrete from Continuous. Then you only have the selected dates, which is exactly what we want.

This is just showing all the rows per Game Date, but we can add Event Type to Filter again and just select BLOCK, GOAL, MISS, SHOT. This shows a line graph for both teams during the game, but if we wanted to, we could add something to the Color mark to make multiple lines. If we go back to the data field we created earlier, which is just a yes/no field that determines whether the team is Philadelphia or their opponent, and bring that to Color, you can see here that it creates multiple lines.

The last thing I want to show on this graph (again, we're just trying to touch on a lot of the basic Tableau functionalities) is that I want to introduce the concept of a reference line. If you right click on any numeric axis, there should be an option to Add Reference Line. Again, you can get very complex with your reference lines, but this one is going to be really basic, so basic that it's the default reference line. It's taking the value of that axis, which here is the sum of the Number of Records, and we want to show the average. We're going to change the scope up here to the Entire Table, and you can see that it creates an average line. You can get very fancy with how you calculate these reference lines, but we'll keep it really simple for now. You can change the label, if I want it to say Average Number of Shots, you can set what the tooltip looks like, you can format what the line looks like, if we want an orange line like this. This is a very useful feature in Tableau that makes it easy to look at data aggregated at different levels within the same view. There are much more complex ways to do that, we'll very briefly touch on it, but this is a useful way if the measure you're interested in is fairly simple.

## Scatterplot (33:45)

We have been looking, in some of our previous charts, at our Event Type field filtered down into different groups. But for a scatterplot, we're going to make a couple of calculated fields so that we can compare them. If we go to the Analysis menu, then Create Calculated Field, all we're going to do is create two calculated fields, one is going to isolate the GOAL values and the other will isolate GOAL and SHOT. You can do that individually by filtering the view, as we've been doing, but since we want to compare them both at the same time in the same view, it's just easier to create some simple calculated fields. Our Goals calculated field: IF Event Type = "GOAL" THEN 1 ELSE 0 END. Our Shots calculated field: IF Event Type = "GOAL" OR Event Type = "SHOT" THEN 1 ELSE 0 END.

Move the Shots data field to Columns, the Goals data field to Rows. This does not look like a standard scatterplot, and that's because Tableau as a default likes to aggregate data. This one little dot that shows up on this pathetic scatterplot shows all the goals and all the shots. That's not what we're interested in for this particular exercise, we want to see a scatterplot of shots versus goals for every team in each game. So all we have to do in order to do that is add those fields over here onto the Detail option on the Marks card. If we drag Game ID onto Detail, now we have four dots, one for each game, which is progress. If we also add Event Team onto detail, there we go, now we have eight dots. This particular dot at 0,0 is showing up because there are some rows with an Event Team of NA. To get rid of those, all we have to do is select our Event Team pill, click Filter, and uncheck NA.

Now we have a scatterplot that isn't formatted in any customized way but looks how we want it to look. If we wanted to make these dots into filled-in circles, as opposed to empty circles, go onto the Marks card and change to Circle. We can also make them bigger by adjusting the size, and if we want to do color, we can use our PHI calculated field and drag that onto color. You can see that this maintains the color palette we created for this field previously. All of the Philadelphia circles are orange, and the other teams are gray. You can also add labels, if we wanted to add Event Team, we can just drag that field onto Label, and then you could customize those.

## Chart with dual axis (37:38)

This next one we're going to build is a really helpful skill to learn in Tableau. We're going to learn how to make what's basically a bar chart but with a dual axis. We're going to do this in a really simple way, and this is a good gateway into how to make really neat-looking custom graphs in Tableau. The dual axis is a really powerful feature to know. A big learning curve is Tableau is learning how to display data at different levels of aggregation in the same view. We showed it before when we made the reference line in our line graph, that's one really easy way to do it, this dual axis method is a way to explore it, and you can also do this with calculations (and that won't be the focus of this video because it's getting a little too complex).

Here, we're going to make a dual axis chart that shows how many shots a player got in all of these games, compared to what their average per game was. So we're looking at different levels of aggregation in the same view. In this example, I'm only interested in the Philadelphia players because they played the most games, so I'm going to drag Event Team over to Filter and select Philadelphia. I'm going to filter my Event Type to shot attempts (BLOCK, GOAL, MISS, SHOT), and then I'm going to bring my Event Player 1 field onto Columns. This should be old hat now, we're going to add the Number of Records to text and we're going to sort it (again, basically the same as how we built the bar chart in the beginning). 

On our way to building this dual axis chart, I'm going to show how you can make basic cross tabs in Tableau, which are very useful for looking at your data. So again, it's going to look a little ugly for a minute. We're going to take this Measure Names field, which is always the last field in the dimensions section and just has the names of every measure, and bring that up into Columns. We're going to take the partner of the Measure Names field, the Measure Values field, and we're going to bring that over onto Text, to replace the Number of Records field. (But you'll notice that the sort maintains because we did it at the Event Player 1 level.) I'm not interested in all of these fields, so I can just select Filter on the Measure Names pill and uncheck all of them besides Number of Records. You're going to question why I did this, but it makes it easier to show you the next part. So I mentioned that for this dual axis chart, we want to see the total number of shot attempts for each player, which we have listed here already, and we also want to see the average per game. So in order to do that, we need to create an average field. But first, we want to be able to double-check how many games they played. It's nice, when you're creating calculations in Tableau, to create them iteratively like this to make sure it's aggregating as you expect and that the math is right.

We're going to take our Game ID field, which is our unique identifier for each game, and we're going to drag that into this Measure Values box. Tableau does not like that, as you can see, because we have Game ID set up as a dimension but are asking it to act like a measure. We can get around this, all you have to do is select the Game ID pill and go down to Measure, then we're going to ask it to, instead of acting as a string, act as a measure with a distinct count. We can see that most of these players played in all four games, a couple only played in three, etc. We're going to go to the Analysis menu, Create Calculated Field, and we're going to call this Player Average: SUM(Number of Records) / COUNTD(Game Id). That will create a new data field that we can drag into our Measure Values box, and you can spot check that it is calculating correctly.

Now we're going to bring Number of Records to Columns, we're also going to take Player Average and also bring that to Columns. Now you basically have two bar charts, one for Number of Records and one for Player Average. We're going to right-click on the Player Average axis and select Dual Axis, which will bring them together. The most important step is to again right-click on the Player Average axis and select Synchronize Axis, so the axes are lined up properly. In this case I don't really want to show this Player Average axis, so I'll just right-click and uncheck this Show Header option, which will get rid of it. As you can see now here on the Marks card, we have two options, we have our Number of Records axis, and we have our Player Average marks. We can change both of those. I'm going to take the Number of Records section and change it to a bar, I want it to be a bar chart. I can change the color up here, I want it to be a light gray bar. And then in my Player Average section, I like it as a dot, we can stick with this. You could change this to another shape, you could add a label. When you have a dual axis, you just have to remember that you have two options on your Marks card, so you can make changes to both of them or just to one of them. But that's another easy way to show data aggregating at different levels: the total and the average.

## Pie chart (45:35)

The last chart we're going to make, we're going to go through how to make a pie chart. I know pie charts are fairly controversial, we're going to make a very basic pie chart, mostly just to show you how to do it in Tableau. We'll filter down to one game, we'll pick this second one, and we're going to make a pie chart that shows the shot attempts by team, percentage-wise. We'll bring Event Team down to color, and again, we want to get rid of the NA value. We can just right-click on the NA value in the color legend and select Exclude, which is, as you can see, just another way to create a filter. Under the Marks card, we'll change the option to Pie. This makes a half-and-half pie chart. We can use the size option to make it bigger if we want to, but we have to add another field to tell Tableau how we'd like it divided. 

As you can see when you select Pie on the Marks card, there's a new option for Angle. All we're going to do is take our Shots calculated field we created before and drag that right onto Angle. If we wanted to add a label, all we'd have to do is bring our Shots field onto Label, and we now know how to make quick table calculations in Tableau if we wanted a percent of total. We can also format it to show a rounded percentage. A good thing to know about Tableau is that the labels are movable, so you can just move that label straight onto the pie chart if you want. We can change the formatting of the label, we can make it bold, say if we wanted to make it white, we can do that. A compromise that people have reached in the pie chart world is just showing one piece of the pie chart. Say we were only interested in showing the Philadelphia part, this 59 percent section. The easiest way to do that in Tableau, really, is just change the color of the other part of the pie chart and change it to white. Then it looks like you have just one piece of the pie chart.