---
title: "The Anatomy of a Power Kill"
subtitle: "Columbus Blue Jackets Hockey Analytics Conference"
author: "Meghan Hall & Alison Lukan"
date: "2020-02-08"
summary: Examining the rise of the power kill.
categories: ["hockey"]
slides: "https://drive.google.com/file/d/18IyQvNgp-MK0V0-Gul-3OwOasFuuppiK/view"
---
[{{< fa tv >}} SLIDES](https://drive.google.com/file/d/18IyQvNgp-MK0V0-Gul-3OwOasFuuppiK/view){class="btn btn-secondary" target="_blank"}

During the 2018-19 season, the penalty kill for the Columbus Blue Jackets set a modern-era record with nearly 25 percent of the total unblocked shot attempts while their opponent was on the power play. This style of aggressive, offensive play on the penalty kill is not limited to the Blue Jackets (the share of shots on goal, league wide, by the penalty killing team has increased from 14 percent in 2014 to nearly 19 percent last season) and has given rise to a new term–the power kill. This talk will build on both presenters' prior work on the penalty kill and discuss 1) how certain teams are utilizing the power kill and 2) why more teams should adopt it as a strategy. Existing regularized adjusted plus-minus metrics will be used to determine whether coaches are selecting more offensively-minded players for the penalty kill, and the systems and strategies of teams using the power kill approach will be broken down. The two presenters have compiled dozens of hours of tracking data for penalty kills, which will be used to examine the defensive impact of adopting aggressive play; quantify the usefulness of that aggressive play, considering the decreasing defensive skill of power play players and the increasing prevalence of the four-forward power play; and describe how teams are looking at penalty kill effectiveness in new ways.
