---
title: "Tracking Increasing Offense on the Penalty Kill"
subtitle: "Rochester Institute of Technology Sports Analytics Conference"
author: "Meghan Hall"
date: "2019-09-14"
summary: Examining the last four seasons of NHL data to explore the trend of increasing offense on the penalty kill.
categories: ["hockey"]
slides: "https://drive.google.com/file/d/1dfygDHJb7V1FhYlcviTw4oYpa5BmD6iR/view"
---
[{{< fa tv >}} SLIDES](https://drive.google.com/file/d/1dfygDHJb7V1FhYlcviTw4oYpa5BmD6iR/view){class="btn btn-secondary" target="_blank"} [{{< fa chart-column >}} DATA](https://public.tableau.com/views/IncreasingOffenseonthePenaltyKill/PKOffense?:language=en-US&:display_count=n&:origin=viz_share_link){class="btn btn-secondary" target="_blank"}

The share of shots on goal taken by the penalty killing team on 5v4 penalties has increased from 14 percent in the 2015-16 season to nearly 19 percent in the 2018-19 season. There were increases of similar magnitude for shot attempts, unblocked shot attempts, and expected goals, and a smaller increase in the share of goals. The goals of this project are to 1) investigate and discuss possible reasons for how and why this might be happening and 2) further analyze the risk-reward balance of aggressive offensive play on the penalty kill. Existing regularized adjusted plus-minus metrics are used to determine whether the offensive and defensive skill of penalty kill and power play players, respectively, is changing and whether coaches are selecting more offensively-minded players for the penalty kill. The positional breakdown of power plays is also discussed, along with tracking data from over 500 minutes of special teams play last season, to determine whether there could be a link between the increasing prevalence of the four-forward power play and the increasing offense seen on the penalty kill. Additionally, the penalty kill aggressiveness metric developed by Matt Cane to quantify, using zone entry data, how often teams pursue offensive opportunities on the penalty kill is updated for the previous three seasons and examined for relationships to offensive and defensive success on the penalty kill.
